"""change about me length

Revision ID: 142945908582
Revises: 69332dea058b
Create Date: 2025-04-30 18:32:09.404802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142945908582'
down_revision = '69332dea058b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
