"""add access token in services table

Revision ID: 1618861069d6
Revises: fb636901e70d
Create Date: 2025-04-27 14:35:47.783728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1618861069d6'
down_revision = 'fb636901e70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_access_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('expires_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requested_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('requested_at')
        batch_op.drop_column('expires_in')
        batch_op.drop_column('_access_token')

    # ### end Alembic commands ###
