"""create user_services table

Revision ID: 17582f7d8417
Revises: ba51d2d8a9bf
Create Date: 2025-03-25 00:53:52.172880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17582f7d8417'
down_revision = 'ba51d2d8a9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_services',
    sa.Column('user_services_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_services_id')
    )
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_services_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_services_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_services_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_services_service_id'))

    op.drop_table('user_services')
    # ### end Alembic commands ###
