"""define relationships

Revision ID: 2dcef1c0bbb5
Revises: ba51d2d8a9bf
Create Date: 2025-03-25 05:39:10.405181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcef1c0bbb5'
down_revision = 'ba51d2d8a9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_services',
    sa.Column('user_services_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_services_id')
    )
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_services_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_services_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_url',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_services_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_services_service_id'))

    op.drop_table('user_services')
    # ### end Alembic commands ###
