"""Add column for profile privacy (private/public)

Revision ID: 3f3d4e10994b
Revises: db333145f5b3
Create Date: 2025-06-25 02:21:07.724217

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f3d4e10994b"
down_revision = "db333145f5b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_profile_public",
                sa.Boolean(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_profile_public")

    # ### end Alembic commands ###
