"""add requested at field for user_services

Revision ID: 5a13795107f3
Revises: c7a5d3a68b6c
Create Date: 2025-04-03 13:36:53.800225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a13795107f3'
down_revision = 'c7a5d3a68b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_column('requested_at')

    # ### end Alembic commands ###
