"""add user profile url

Revision ID: 69332dea058b
Revises: 0e5936dd6785
Create Date: 2025-04-30 03:23:11.086977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69332dea058b'
down_revision = '0e5936dd6785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###
