"""Add secret seen column to OAuth client

Revision ID: 78e2f13bcfc7
Revises: 3f3d4e10994b
Create Date: 2025-08-06 01:37:33.508974

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78e2f13bcfc7"
down_revision = "3f3d4e10994b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth2_client", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "secret_seen",
                sa.Boolean(),
                server_default=sa.text("FALSE"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth2_client", schema=None) as batch_op:
        batch_op.drop_column("secret_seen")

    # ### end Alembic commands ###
