"""Add username field to UserService

Revision ID: 7bf4c19c1edd
Revises: a13c963ff140
Create Date: 2025-04-24 06:24:07.679024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf4c19c1edd'
down_revision = 'a13c963ff140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
