"""Add unique constraint to user_services

Revision ID: a13c963ff140
Revises: 5a13795107f3
Create Date: 2025-04-24 05:07:44.818276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13c963ff140'
down_revision = '5a13795107f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_service', ['user_id', 'service_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_service', type_='unique')

    # ### end Alembic commands ###
