"""add encryption & decryption

Revision ID: a7312f8d8304
Revises: 2dcef1c0bbb5
Create Date: 2025-03-25 07:46:23.606937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7312f8d8304'
down_revision = '2dcef1c0bbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_access_token', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('_refresh_token', sa.String(length=256), nullable=True))
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.String(length=128), nullable=False))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users__email'), ['_email'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users__email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)
        batch_op.drop_column('_email')

    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('_refresh_token')
        batch_op.drop_column('_access_token')

    # ### end Alembic commands ###
