"""add users_data table

Revision ID: c48e1b318077
Revises: 6f6d3ac56c8d
Create Date: 2025-04-01 03:52:30.211036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48e1b318077'
down_revision = '6f6d3ac56c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_data',
    sa.Column('user_data_id', sa.Integer(), nullable=False),
    sa.Column('user_service_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_service_id'], ['user_services.user_services_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_data_id'),
    sa.UniqueConstraint('user_service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_data')
    # ### end Alembic commands ###
