"""empty message

Revision ID: db333145f5b3
Revises: d75837cfd696
Create Date: 2025-05-29 07:24:58.875968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db333145f5b3'
down_revision = 'd75837cfd696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('amr', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_code', schema=None) as batch_op:
        batch_op.drop_column('amr')
        batch_op.drop_column('acr')

    # ### end Alembic commands ###
