"""Make access token optional/nullable

Revision ID: fb636901e70d
Revises: 7bf4c19c1edd
Create Date: 2025-04-24 06:39:31.571706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb636901e70d'
down_revision = '7bf4c19c1edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.alter_column('_access_token',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_services', schema=None) as batch_op:
        batch_op.alter_column('_access_token',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
